CREATE TABLE heartbeats (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	_created		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	odometer		NUMERIC NOT NULL,
	fuel			NUMERIC NOT NULL,
	place_id		LONG,
	sync_id			TEXT,
	sync_etag		TEXT,
	sync_state		LONG NOT NULL DEFAULT 0,
	sync_date		TIMESTAMP,
	modified		TIMESTAMP DEFAULT (strftime('%s', 'now')),
	type			INTEGER,
	name			TEXT,
	distance		NUMERIC,
	amount			NUMERIC,
	unit_price		NUMERIC,
	cost			NUMERIC,
	vehicle_id		LONG,
	track_id		LONG,
	transaction_id LONG);